-- ==========================================
-- ASHIKA — Seed Product Data
-- ==========================================
-- Initial product catalog

INSERT INTO products (sku, name, slug, category, subcategory, occasion, color, colors, rental_price, retail_price, tier, sizes, description, fabric, work, blouse_included, accessories_included, images, thumbnail, status, featured) VALUES

-- Sarees
('ASH-SAR-001', 'Royal Blue Banarasi Silk Saree', 'royal-blue-banarasi-silk-saree', 'saree', 'banarasi', ARRAY['wedding', 'festival'], 'blue', ARRAY['blue', 'gold'], 129.00, 650.00, 'lite', '[{"size": "Free Size", "quantity": 2, "available": 2}]', 'Exquisite Banarasi silk saree with intricate zari work, perfect for weddings and special occasions.', 'Pure Silk', 'Zari Work', true, ARRAY[]::text[], ARRAY['https://images.pexels.com/photos/7442282/pexels-photo-7442282.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/7442282/pexels-photo-7442282.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', true),

('ASH-SAR-002', 'Red Kanjeevaram Bridal Saree', 'red-kanjeevaram-bridal-saree', 'saree', 'kanjeevaram', ARRAY['wedding'], 'red', ARRAY['red', 'gold'], 189.00, 950.00, 'premium', '[{"size": "Free Size", "quantity": 2, "available": 2}]', 'Traditional Kanjeevaram silk saree with temple border, ideal for South Indian weddings.', 'Kanjeevaram Silk', 'Temple Border', true, ARRAY[]::text[], ARRAY['https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', true),

('ASH-SAR-003', 'Emerald Green Silk Saree', 'emerald-green-silk-saree', 'saree', NULL, ARRAY['festival', 'party'], 'green', ARRAY['green', 'gold'], 99.00, 450.00, 'lite', '[{"size": "Free Size", "quantity": 3, "available": 3}]', 'Elegant green silk saree with embroidery work, perfect for festive occasions.', 'Pure Silk', 'Embroidery', true, ARRAY[]::text[], ARRAY['https://images.pexels.com/photos/7442282/pexels-photo-7442282.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/7442282/pexels-photo-7442282.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', false),

('ASH-SAR-004', 'Pink Chiffon Party Saree', 'pink-chiffon-party-saree', 'saree', NULL, ARRAY['party', 'engagement'], 'pink', ARRAY['pink'], 79.00, 350.00, 'lite', '[{"size": "Free Size", "quantity": 2, "available": 2}]', 'Lightweight pink chiffon saree with sequin work, perfect for parties.', 'Chiffon', 'Sequins', true, ARRAY[]::text[], ARRAY['https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', false),

('ASH-SAR-005', 'Gold Tissue Saree', 'gold-tissue-saree', 'saree', NULL, ARRAY['wedding', 'reception'], 'gold', ARRAY['gold'], 149.00, 700.00, 'lite', '[{"size": "Free Size", "quantity": 2, "available": 2}]', 'Stunning gold tissue saree with self work, perfect for receptions.', 'Tissue', 'Self Work', true, ARRAY[]::text[], ARRAY['https://images.pexels.com/photos/7442282/pexels-photo-7442282.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/7442282/pexels-photo-7442282.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', true),

('ASH-SAR-006', 'Wine Red Velvet Saree', 'wine-red-velvet-saree', 'saree', NULL, ARRAY['wedding', 'party'], 'wine', ARRAY['wine', 'maroon'], 169.00, 800.00, 'premium', '[{"size": "Free Size", "quantity": 2, "available": 2}]', 'Luxurious wine red velvet saree with stone border, perfect for winter celebrations.', 'Velvet', 'Stone Border', true, ARRAY[]::text[], ARRAY['https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', true),

-- Lehengas
('ASH-LEH-001', 'Maroon Bridal Lehenga', 'maroon-bridal-lehenga', 'lehenga', 'bridal', ARRAY['wedding'], 'maroon', ARRAY['maroon', 'gold'], 249.00, 1200.00, 'premium', '[{"size": "S", "quantity": 1, "available": 1}, {"size": "M", "quantity": 2, "available": 2}, {"size": "L", "quantity": 1, "available": 1}]', 'Stunning bridal lehenga with heavy hand embroidery, perfect for the big day.', 'Pure Silk', 'Heavy Embroidery', true, ARRAY['dupatta'], ARRAY['https://images.pexels.com/photos/8881954/pexels-photo-8881954.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/8881954/pexels-photo-8881954.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', true),

('ASH-LEH-002', 'Teal Blue Designer Lehenga', 'teal-blue-designer-lehenga', 'lehenga', NULL, ARRAY['sangeet', 'reception'], 'teal', ARRAY['teal', 'silver'], 179.00, 850.00, 'premium', '[{"size": "S", "quantity": 1, "available": 1}, {"size": "M", "quantity": 2, "available": 2}, {"size": "L", "quantity": 1, "available": 1}]', 'Designer teal lehenga with mirror work, perfect for sangeet night.', 'Georgette', 'Mirror Work', true, ARRAY['dupatta'], ARRAY['https://images.pexels.com/photos/8750043/pexels-photo-8750043.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/8750043/pexels-photo-8750043.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', false),

('ASH-LEH-003', 'Pink Floral Lehenga', 'pink-floral-lehenga', 'lehenga', NULL, ARRAY['mehendi', 'engagement'], 'pink', ARRAY['pink', 'green'], 149.00, 700.00, 'lite', '[{"size": "XS", "quantity": 1, "available": 1}, {"size": "S", "quantity": 2, "available": 2}, {"size": "M", "quantity": 2, "available": 2}, {"size": "L", "quantity": 1, "available": 1}]', 'Fresh pink lehenga with floral embroidery, perfect for mehendi ceremonies.', 'Net', 'Floral Embroidery', true, ARRAY['dupatta'], ARRAY['https://images.pexels.com/photos/8881954/pexels-photo-8881954.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/8881954/pexels-photo-8881954.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', false),

('ASH-LEH-004', 'Mustard Festive Lehenga', 'mustard-festive-lehenga', 'lehenga', NULL, ARRAY['festival', 'garba'], 'mustard', ARRAY['mustard', 'red'], 159.00, 750.00, 'premium', '[{"size": "S", "quantity": 1, "available": 1}, {"size": "M", "quantity": 2, "available": 2}, {"size": "L", "quantity": 1, "available": 1}]', 'Vibrant mustard lehenga with mirror and thread work, perfect for Navratri.', 'Cotton Silk', 'Mirror & Thread', true, ARRAY['dupatta'], ARRAY['https://images.pexels.com/photos/8750043/pexels-photo-8750043.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/8750043/pexels-photo-8750043.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', true),

-- Sherwanis
('ASH-SHE-001', 'Ivory Wedding Sherwani', 'ivory-wedding-sherwani', 'sherwani', NULL, ARRAY['wedding'], 'ivory', ARRAY['ivory', 'gold'], 199.00, 900.00, 'premium', '[{"size": "S", "quantity": 1, "available": 1}, {"size": "M", "quantity": 2, "available": 2}, {"size": "L", "quantity": 2, "available": 2}, {"size": "XL", "quantity": 1, "available": 1}]', 'Elegant ivory sherwani with golden thread work, perfect for grooms.', 'Raw Silk', 'Thread Work', false, ARRAY['stole', 'churidar'], ARRAY['https://images.pexels.com/photos/28758797/pexels-photo-28758797.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/28758797/pexels-photo-28758797.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', true),

('ASH-SHE-002', 'Maroon Royal Sherwani', 'maroon-royal-sherwani', 'sherwani', NULL, ARRAY['wedding', 'reception'], 'maroon', ARRAY['maroon', 'gold'], 179.00, 850.00, 'premium', '[{"size": "S", "quantity": 1, "available": 1}, {"size": "M", "quantity": 2, "available": 2}, {"size": "L", "quantity": 1, "available": 1}, {"size": "XL", "quantity": 1, "available": 1}]', 'Royal maroon sherwani with zardozi work, perfect for the groom.', 'Velvet', 'Zardozi', false, ARRAY['stole'], ARRAY['https://images.pexels.com/photos/28758797/pexels-photo-28758797.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/28758797/pexels-photo-28758797.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', false),

('ASH-SHE-003', 'Black Indo-Western Sherwani', 'black-indo-western-sherwani', 'sherwani', 'indo-western', ARRAY['reception', 'party'], 'black', ARRAY['black', 'silver'], 149.00, 700.00, 'lite', '[{"size": "M", "quantity": 2, "available": 2}, {"size": "L", "quantity": 2, "available": 2}, {"size": "XL", "quantity": 1, "available": 1}]', 'Modern black indo-western sherwani, perfect for reception parties.', 'Jacquard', 'Modern Cut', false, ARRAY[]::text[], ARRAY['https://images.pexels.com/photos/28758797/pexels-photo-28758797.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/28758797/pexels-photo-28758797.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', false),

('ASH-SHE-004', 'Navy Blue Classic Sherwani', 'navy-blue-classic-sherwani', 'sherwani', NULL, ARRAY['wedding', 'engagement'], 'navy', ARRAY['navy', 'gold'], 129.00, 600.00, 'lite', '[{"size": "S", "quantity": 1, "available": 1}, {"size": "M", "quantity": 2, "available": 2}, {"size": "L", "quantity": 2, "available": 2}]', 'Classic navy blue sherwani with self jacquard pattern.', 'Jacquard', 'Self Jacquard', false, ARRAY['churidar'], ARRAY['https://images.pexels.com/photos/28758797/pexels-photo-28758797.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/28758797/pexels-photo-28758797.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', false),

-- Salwar Kameez
('ASH-SAL-001', 'Red Anarkali Suit', 'red-anarkali-suit', 'salwar_kameez', 'anarkali', ARRAY['festival', 'party'], 'red', ARRAY['red', 'gold'], 109.00, 500.00, 'lite', '[{"size": "S", "quantity": 1, "available": 1}, {"size": "M", "quantity": 2, "available": 2}, {"size": "L", "quantity": 2, "available": 2}, {"size": "XL", "quantity": 1, "available": 1}]', 'Flowing Anarkali suit with intricate embroidery, perfect for festive occasions.', 'Georgette', 'Embroidery', false, ARRAY['dupatta'], ARRAY['https://images.pexels.com/photos/7442282/pexels-photo-7442282.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/7442282/pexels-photo-7442282.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', true),

('ASH-SAL-002', 'Yellow Sharara Set', 'yellow-sharara-set', 'salwar_kameez', 'sharara', ARRAY['mehendi', 'haldi'], 'yellow', ARRAY['yellow', 'gold'], 129.00, 600.00, 'lite', '[{"size": "S", "quantity": 1, "available": 1}, {"size": "M", "quantity": 2, "available": 2}, {"size": "L", "quantity": 1, "available": 1}]', 'Bright yellow sharara set with gota patti work, perfect for haldi ceremony.', 'Cotton Silk', 'Gota Patti', false, ARRAY['dupatta'], ARRAY['https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', false),

('ASH-SAL-003', 'Mint Green Palazzo Suit', 'mint-green-palazzo-suit', 'salwar_kameez', 'palazzo', ARRAY['casual', 'festival'], 'mint', ARRAY['mint', 'white'], 89.00, 400.00, 'lite', '[{"size": "S", "quantity": 2, "available": 2}, {"size": "M", "quantity": 2, "available": 2}, {"size": "L", "quantity": 2, "available": 2}]', 'Elegant mint green palazzo suit with thread work.', 'Cotton', 'Thread Work', false, ARRAY['dupatta'], ARRAY['https://images.pexels.com/photos/7442282/pexels-photo-7442282.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/7442282/pexels-photo-7442282.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', false),

('ASH-SAL-004', 'Peach Straight Cut Suit', 'peach-straight-cut-suit', 'salwar_kameez', 'straight', ARRAY['casual', 'office'], 'peach', ARRAY['peach'], 79.00, 350.00, 'lite', '[{"size": "S", "quantity": 2, "available": 2}, {"size": "M", "quantity": 3, "available": 3}, {"size": "L", "quantity": 2, "available": 2}]', 'Simple peach straight cut suit, perfect for casual occasions.', 'Cotton Silk', 'Print', false, ARRAY['dupatta'], ARRAY['https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=1200&h=1600&fit=crop'], 'https://images.pexels.com/photos/1162983/pexels-photo-1162983.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop', 'available', false);
